### ISSUE TITLE
Not all open links to external files work?

### ISSUE THREAD

**Issue by ctr26** [imjoy-team/imagej.js#22]
Hi all,

These links do work:
https://ij.imjoy.io/?open=https://github.com/imjoy-team/imagej.js/blob/master/src/assets/img/screenshot-1.png

These links do not:
https://ij.imjoy.io/?open=https://www.ebi.ac.uk/biostudies/files/S-EPMC7453447/Supplementary_Figure_1.png
https://ij.imjoy.io/?open=https://www.ebi.ac.uk/biostudies/files/S-BSST518/sFig_1.tif

Is it a problem on the ebi's end blocking access to the files from imjoy's servers?

**Comment by oeway** [comment]
Hi @ctr26 , thanks for reporting.

Yes, the problem is from ebi's server.

In the Chrome developer tool, I see the following error for those doesn't work:
```
Access to fetch at 'https://www.ebi.ac.uk/biostudies/files/S-EPMC7453447/Supplementary_Figure_1.png' from origin 'https://ij.imjoy.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
The solutions are: 

1) host these files elsewhere, github or Zenodo 

2) talk to the IT of EBI to enable CORS for two of our domains: `https://ij.imjoy.io` and `https://imjoy.io`.

**Comment by ctr26** [comment]
Will do (2) thanks

**Comment by mutterer** [comment]
Similar issue exists for files hosted on Figshare, example:
https://ij.imjoy.io/?run=https://ndownloader.figshare.com/files/24761820

**Comment by mutterer** [comment]
For the record, I inquired about CORS support for figshare.com, and got the following response:

```
Regarding fetching data from Figshare, we do offer a REST-full API: https://docs.figshare.com/ and also a widgets service https://figshare.com/blog/embeddable_figshare_content/87
We believe that these two public services offer the functionality you require.
```

**Comment by oeway** [comment]
Thanks @mutterer 
Yes, I think we just need to find a way to convert the url into their api (just like I did for Zenodo), can you point me to the page where you store your ijm file?

**Comment by mutterer** [comment]
Here's an example page (not mine).
https://ndownloader.figshare.com/files/24761820

**Comment by oeway** [comment]
I just investigate a bit into their API document, it seems they don't support CORS for their download URL.

We can list the article details: https://docs.figshare.com/#article_details, for example: https://api.figshare.com/v2/articles/5685874/files/9954838
This will return information about the file, however, it doesn't help much because the returned json object said `"download_url": "https://ndownloader.figshare.com/files/9954838"` which point to the same download url that doesn't support CORS.

If paste `https://ndownloader.figshare.com/files/9954838` into the browser, it actually redirects to `https://s3-eu-west-1.amazonaws.com/pstorage-plos-3567654/9954838/Fig11.tif`, and this is the acttual url which can potentially work because it contains the actual file name and extension (needed for infer file format).

If I try `https://ij.imjoy.io/?open=https://s3-eu-west-1.amazonaws.com/pstorage-plos-3567654/9954838/Fig11.tif`, I got the CORS error:
```
Access to fetch at 'https://s3-eu-west-1.amazonaws.com/pstorage-plos-3567654/9954838/Fig11.tif' from origin 'https://ij.imjoy.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```

I think we need to ask them see if it's possible to: 
1. have an api to infer the actual file url with extension, e.g. converting from `https://ndownloader.figshare.com/files/9954838` to `https://s3-eu-west-1.amazonaws.com/pstorage-plos-3567654/9954838/Fig11.tif`
2. enable CORS for all or our two domain names (`https://ij.imjoy.io` and `https://imjoy.io`) on their AWS bucket.
