### ISSUE TITLE
access to app file system

### ISSUE THREAD

**Issue by mutterer** [imjoy-team/imagej.js#45]
getDirectory('imagej'); returns a path, but one cannot create a file there.

![image](https://user-images.githubusercontent.com/711344/101364043-69740280-38a2-11eb-8248-56176a4efba6.png)

**Comment by oeway** [comment]
Right because imagej is served under `/app` which is a http backed mounting point.

If you want to write, you should use `/files` mounting pint, which will be saved under IndexedDB of your browser.
For example the following macro will trigger a file selection dialog, if you "Select Cached Files" (second option), and choose `/files`:
```js
f = File.open(getDirectory("/files") + "test.txt")
print(f, 'test')
File.close(f)
```
Then it will work.

To verify it, you can click in the menu `File --> Open `  choose "Select Cached Files"  and  see the file under /files/test.txt.
<img width="1532" alt="Screenshot 2020-12-14 at 21 18 27" src="https://user-images.githubusercontent.com/478667/102131065-f0504e80-3e51-11eb-9a65-2f4c0360dfee.png">


I think a future plan is to support https://github.com/jvilk/BrowserFS which can enable many different backend, but this will require some support from cheerpj.

**Comment by mutterer** [comment]
This works fine indeed, thanks @oeway !
