### ISSUE TITLE
Support for more dimensions in ij.viewImage()

### ISSUE THREAD

**Issue by will-moore** [imjoy-team/imagej.js#56]
As I found at https://github.com/will-moore/omero-imjoy/issues/5 (initially thinking this was an error), I now realise that `ij.viewImage()` only supports 3 dimensions for non-rgb data: `shape [z-stack, height, width, 1]`.

I would really like to view multi-channel Z-stacks, Time-lapses or both (5D).

As the size of images increases, support for a virtual image (#53) will become more important, but the 3D limit is the current limitation.

Regards,
  Will.

**Comment by oeway** [comment]
Hi @will-moore Right, because the current implementation is based on the ["Raw..." command](https://github.com/imjoy-team/imagej.js/blob/d93c6f21922e9c31bbcf85f33548c8c9bf971c2a/src/index.js#L502-L535), so we only support single channel or RGB image stacks. However, you can pass reshape your data into a single channel stack, then run a "Stack to HyperStack" macro to convert it, for example:
```js
ij.runMacro(`run("Stack to Hyperstack...", "order=xyczt(default) channels=2 slices=5 frames=51 display=Grayscale");`)
```

Yes, I think the best way forward is to implement a lazy virtual image interface. In fact I have investigated this and asked Wayne about it, it seems straightforward and there are examples to follow. Like this we will be able to hook up directly with zarr.js, such that we just need to pass a zarr store to it. I will try to find some time to implement this.

**Comment by will-moore** [comment]
That worked very well, thanks!
