### ISSUE TITLE
The page no longer loads, it shows me an error of ij-1.53m.jar

### ISSUE THREAD

**Issue by KevinHdezVaz** [imjoy-team/imagej.js#72]
Hello, when entering the ImageJ.JS web page it does not allow me to advance from the page on the left, from what you can see on the network it seems that "ij-1.53m" was deleted or deleted. jar" from the repository.
I hope you can take a look.
![Captura de Pantalla 2022-05-12 a la(s) 7 04 55 p m](https://user-images.githubusercontent.com/74629182/168460259-05b86f28-da00-4fec-81ad-5f4713e3bd4e.png)

**Comment by oeway** [comment]
Hi @KevinHdezVaz Thanks for reporting, the issue was because a bug in the CI, and a unmerged PR with imagej-1.53o was released. [Here](https://github.com/imjoy-team/ImageJA.JS/commit/29749be1b53c27085af8dda970afc724adeef920) is the fix.

I have deleted that release and it should work after the CI finished the build.

**Comment by oeway** [comment]
@KevinHdezVaz Could you check if it works for you? There is another bug in the service worker which it try to cache broken link, so you might need to clear the site cache too. Please let me know if it works without clear cache but only reload the pages for a few times.

**Comment by KevinHdezVaz** [comment]
Before warning by this means, if it worked in the browser (do not delete the im.imjoy.io cache) and when starting it in incognito mode, it did not load, it was waiting.
Now yes, everything works perfectly :)
